apiVersion: apps/v1
kind: ConfigMap
metadata:
  name: eureka-cm
data:
  eureka_server_address: http://localhost:8761/eureka

---

apiVersion: v1
kind: Service
metadata:
  name: eureka
  labels:
    app: eureka
spec:
  clusterIP: None
  ports:
    -port: 8761
    name: eureka
  selector:
    app: eureka
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eureka-cm
spec:
  serviceName: "eureka"
  replicas: 1
  selector:
    mathchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
        - name: eureka
          image: yaroslavpetrovskiy/eureka-server:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8761
          env:
            - name: EUREKA_SERVER_ADDRESS
              valueForm:
                configMapKeyRef:
                  name: eureka-cm
                  key: eureka_service_address

---
apiVersion: v1
kind: Service
metadata:
  name: eureka-lb
  labels:
    app: eureka
spec:
  selcetor:
    app: eureka
    type: NodePort
    ports:
      - port: 80
        targetPort: 8761
